'use strict';
var submitButton = document.querySelector('#submit');
var responseURL = document.querySelector('.response');
var form = document.querySelector('form');
var fr = new FileReader();
let json = {};
const allInputs = document.querySelectorAll('input');
const tweetButton = document.querySelector('#tweetButton');
const twitterText = 'Check out my virtual calling card';
let twitterURL;

getLocalStorage();
function getLocalStorage() {
  const savedInputs = JSON.parse(localStorage.getItem('form'));
  console.log('form', savedInputs);
  console.log('allInputs', allInputs);
  allInputs.forEach((input) => {
    for (const key in savedInputs) {
      if (key === input.id) {
        console.log(key, input.id, 'they are equal');
        input.value = savedInputs[key];
      }
    }
  });
}

submitButton.addEventListener('click', loadPhoto);

function sendData() {
  var inputs = Array.from(form.elements);
  console.log('inputs', inputs);
  json = getJSONFromInputs(inputs);
  json.skills = ['JavaScript', 'React'];
  json.photo = fr.result; /* adds photo base64 to object*/
  console.log('json', json);
  /*to set up local storage from json object*/
  localStorage.setItem('form', JSON.stringify(json));
  sendRequest(json);
}

function loadPhoto() {
  var myFile = document.querySelector('#img-selector').files[0];
  fr.addEventListener('load', sendData);
  fr.readAsDataURL(myFile);
}

function getJSONFromInputs(inputs) {
  return inputs.reduce(function (json, val) {
    if (val.nodeName !== 'BUTTON') json[val.name] = val.value;
    localStorage.setItem('form', JSON.stringify(json));
    return json; /* object with all input values except photo*/
  }, {});
}

function sendRequest(json) {
  fetch('https://us-central1-awesome-cards-cf6f0.cloudfunctions.net/card/', {
    method: 'POST',
    body: JSON.stringify(json),
    headers: {
      'content-type': 'application/json',
    },
  })
    .then(function (resp) {
      return resp.json();
    })
    .then(function (result) {
      showURL(result);
    })
    .catch(function (error) {
      console.log(error);
    });
}

function showURL(result) {
  if (result.success) {
    responseURL.innerHTML =
      '<a href=' + result.cardURL + '>' + result.cardURL + '</a>';
    twitterURL = result.cardURL;
  } else {
    responseURL.innerHTML = 'ERROR:' + result.error;
  }
}
tweetButton.addEventListener('click', getTwitterURL);
function getTwitterURL() {
  /* takes url generated by api and adds it to Twitter post url (and tweet message, if desired) to create tweet*/
  tweetButton.setAttribute(
    'href',
    `https://twitter.com/intent/tweet?text=hi my name is kayla&url=${twitterURL}`
  );
}
